CreditLens Data Analysis

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("credit_risk_dataset.csv")

In [4]:
df.shape
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32581 entries, 0 to 32580
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   person_age                  32581 non-null  int64
 1   person_income               32581 non-null  int64
 2   person_home_ownership       32581 non-null  object
 3   person_emp_length           31686 non-null  float64
 4   loan_intent                 32581 non-null  object
 5   loan_grade                  32581 non-null  object
 6   loan_amnt                   32581 non-null  int64
 7   loan_int_rate               29465 non-null  float64
 8   loan_status                 32581 non-null  int64
 9   loan_percent_income         32581 non-null  float64
 10  cb_person_default_on_file   32581 non-null  object
 11  cb_person_cred_hist_length  32581 non-null  int64
dtypes: float64(3), int64(5), object(4)
memory usage: 3.0+ MB

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_cred_hist_length
count,32581.000000,3.258100e+04,31686.000000,32581.000000,29465.000000,32581.000000,32581.000000,32581.000000
mean,27.734600,6.607485e+04,4.789686,9589.371106,11.011695,0.218164,0.170203,5.804211
std,6.348078,6.198312e+04,4.142630,6322.086646,3.240459,0.413006,0.106782,4.055001
min,20.000000,4.000000e+03,0.000000,500.000000,5.420000,0.000000,0.000000,2.000000
25%,23.000000,3.850000e+04,2.000000,5000.000000,7.900000,0.000000,0.090000,3.000000
50%,26.000000,5.500000e+04,4.000000,8000.000000,10.990000,0.000000,0.150000,4.000000
75%,30.000000,7.920000e+04,7.000000,12200.000000,13.470000,0.000000,0.230000,8.000000
max,144.000000,6.000000e+06,123.000000,35000.000000,23.220000,1.000000,0.830000,30.000000

In [5]:
df.isnull().sum()

person_age                       0
person_income                    0
person_home_ownership            0
person_emp_length              895
loan_intent                      0
loan_grade                       0
loan_amnt                        0
loan_int_rate                 3116
loan_status                      0
loan_percent_income              0
cb_person_default_on_file        0
cb_person_cred_hist_length       0
dtype: int64

In [6]:
df.isnull()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
32576,False,False,False,False,False,False,False,False,False,False,False,False
32577,False,False,False,False,False,False,False,False,False,False,False,False
32578,False,False,False,False,False,False,False,False,False,False,False,False
32579,False,False,False,False,False,False,False,False,False,False,False,False
32580,False,False,False,False,False,False,False,False,False,False,False,False

In [7]:


df_missing_rate = df[df["person_emp_length"].isna()].head()
df_missing_rate

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
105,22,12600,MORTGAGE,NaN,PERSONAL,A,2000,5.42,1,0.16,N,4
222,24,185000,MORTGAGE,NaN,EDUCATION,B,35000,12.42,0,0.19,N,2
379,24,16800,MORTGAGE,NaN,DEBTCONSOLIDATION,A,3900,NaN,1,0.23,N,3
407,25,52000,RENT,NaN,PERSONAL,B,24000,10.74,1,0.46,N,2
408,22,17352,MORTGAGE,NaN,EDUCATION,C,2250,15.27,0,0.13,Y,3

In [8]:
df_missing_rate1= df[df["loan_int_rate"].isna()].head()
df_missing_rate1

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
39,23,71500,RENT,3.0,DEBTCONSOLIDATION,D,30000,NaN,1,0.42,N,4
50,24,78000,RENT,4.0,DEBTCONSOLIDATION,D,30000,NaN,1,0.38,Y,4
57,23,277000,OWN,3.0,PERSONAL,A,35000,NaN,0,0.13,N,4
59,24,12000,OWN,2.0,VENTURE,E,1750,NaN,0,0.15,Y,3
62,26,263000,MORTGAGE,0.0,EDUCATION,B,10000,NaN,1,0.04,N,4

In [9]:
df.groupby("loan_grade")["loan_int_rate"].apply(
    lambda x: x.isna().sum()
)

loan_grade
A    1003
B    1056
C     630
D     312
E      83
F      27
G       5
Name: loan_int_rate, dtype: int64

In [10]:
df["loan_int_rate"].isna().mean() * 100

np.float64(9.563856235229121)

In [11]:
df["person_emp_length"].isna().mean() * 100

np.float64(2.7469997851508547)

In [12]:
df.groupby("loan_grade")["loan_int_rate"].apply(
    lambda x: x.isna().mean() * 100
)

loan_grade
A     9.306857
B    10.104296
C     9.755342
D     8.604523
E     8.609959
F    11.203320
G     7.812500
Name: loan_int_rate, dtype: float64

In [13]:
df["interest_rate_missing"] = df["loan_int_rate"].isna()

In [14]:
df.groupby("interest_rate_missing")["loan_status"].mean()

interest_rate_missing
False    0.219379
True     0.206675
Name: loan_status, dtype: float64

In [15]:
df.groupby("person_home_ownership")["person_emp_length"].apply(
    lambda x: x.isna().sum()
)

person_home_ownership
MORTGAGE    351
OTHER         0
OWN         174
RENT        370
Name: person_emp_length, dtype: int64

In [16]:
df.groupby("person_home_ownership")["person_emp_length"].apply(
    lambda x: x.isna().mean() * 100
)

person_home_ownership
MORTGAGE    2.610830
OTHER       0.000000
OWN         6.733746
RENT        2.249787
Name: person_emp_length, dtype: float64

In [17]:
df.duplicated().sum()

np.int64(165)

In [18]:
df[df.duplicated()].head(10)

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,interest_rate_missing
15975,23,42000,RENT,5.0,VENTURE,B,6000,9.99,0,0.14,N,4,False
15989,23,90000,MORTGAGE,7.0,EDUCATION,B,8000,10.36,0,0.09,N,3,False
15995,24,48000,MORTGAGE,4.0,MEDICAL,A,4000,5.42,0,0.08,N,4,False
16025,24,10000,RENT,8.0,PERSONAL,A,3000,7.90,1,0.30,N,3,False
16028,23,100000,MORTGAGE,7.0,EDUCATION,A,15000,7.88,0,0.15,N,4,False
16038,26,20000,MORTGAGE,5.0,MEDICAL,A,4800,5.99,0,0.24,N,3,False
16065,22,130000,MORTGAGE,3.0,VENTURE,B,24250,12.18,0,0.19,N,4,False
16070,21,27600,RENT,4.0,EDUCATION,A,7500,6.76,0,0.27,N,4,False
16079,23,26000,RENT,1.0,EDUCATION,B,4000,NaN,0,0.15,N,4,True
16091,23,50000,MORTGAGE,3.0,EDUCATION,A,10000,6.03,0,0.20,N,4,False

In [19]:
df[df.duplicated(keep=False)].sort_values(
    by=list(df.columns)
).head(20)

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,interest_rate_missing
15944,21,8088,RENT,NaN,MEDICAL,C,1200,15.23,0,0.15,Y,2,False
16835,21,8088,RENT,NaN,MEDICAL,C,1200,15.23,0,0.15,Y,2,False
2431,21,15600,RENT,0.0,MEDICAL,A,2800,7.40,1,0.18,N,4,False
17758,21,15600,RENT,0.0,MEDICAL,A,2800,7.40,1,0.18,N,4,False
2498,21,18000,RENT,0.0,DEBTCONSOLIDATION,A,3000,7.90,1,0.17,N,2,False
17601,21,18000,RENT,0.0,DEBTCONSOLIDATION,A,3000,7.90,1,0.17,N,2,False
1778,21,20000,RENT,0.0,MEDICAL,A,2000,NaN,0,0.10,N,3,True
17642,21,20000,RENT,0.0,MEDICAL,A,2000,NaN,0,0.10,N,3,True
740,21,21600,OWN,NaN,VENTURE,A,7125,6.99,0,0.33,N,3,False
17283,21,21600,OWN,NaN,VENTURE,A,7125,6.99,0,0.33,N,3,False
6191,21,26000,RENT,5.0,DEBTCONSOLIDATION,A,6000,7.49,0,0.23,N,2,False
16440,21,26000,RENT,5.0,DEBTCONSOLIDATION,A,6000,7.49,0,0.23,N,2,False
4344,21,26400,RENT,5.0,PERSONAL,C,4750,12.23,0,0.18,N,3,False
16587,21,26400,RENT,5.0,PERSONAL,C,4750,12.23,0,0.18,N,3,False
8206,21,27600,RENT,4.0,EDUCATION,A,7500,6.76,0,0.27,N,4,False
16070,21,27600,RENT,4.0,EDUCATION,A,7500,6.76,0,0.27,N,4,False
1675,21,28692,MORTGAGE,5.0,EDUCATION,B,3000,10.75,0,0.10,N,2,False
17144,21,28692,MORTGAGE,5.0,EDUCATION,B,3000,10.75,0,0.10,N,2,False
13711,21,33009,OWN,5.0,VENTURE,B,12000,11.48,0,0.36,N,4,False
16864,21,33009,OWN,5.0,VENTURE,B,12000,11.48,0,0.36,N,4,False

In [20]:
df = df.drop_duplicates()

In [21]:
df.shape

(32416, 13)

In [22]:
df.duplicated().sum()

np.int64(0)

In [23]:
df["person_age"].describe()

count    32416.000000
mean        27.747008
std          6.354100
min         20.000000
25%         23.000000
50%         26.000000
75%         30.000000
max        144.000000
Name: person_age, dtype: float64

In [24]:
df["person_age"].sort_values(ascending=False).head(10)

32297    144
81       144
183      144
747      123
575      123
32416     94
32506     84
32422     80
32355     78
32534     76
Name: person_age, dtype: int64

In [25]:
df["person_income"].describe()

count    3.241600e+04
mean     6.609164e+04
std      6.201558e+04
min      4.000000e+03
25%      3.854200e+04
50%      5.500000e+04
75%      7.921800e+04
max      6.000000e+06
Name: person_income, dtype: float64

In [26]:
df["loan_amnt"].describe()

count    32416.000000
mean      9593.845632
std       6322.730241
min        500.000000
25%       5000.000000
50%       8000.000000
75%      12250.000000
max      35000.000000
Name: loan_amnt, dtype: float64

In [27]:
df["person_age"].sort_values(ascending=False).head(10)

32297    144
81       144
183      144
747      123
575      123
32416     94
32506     84
32422     80
32355     78
32534     76
Name: person_age, dtype: int64

In [28]:
df[df["person_age"] >= 100]

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,interest_rate_missing
81,144,250000,RENT,4.0,VENTURE,C,4800,13.57,0,0.02,N,3,False
183,144,200000,MORTGAGE,4.0,EDUCATION,B,6000,11.86,0,0.03,N,2,False
575,123,80004,RENT,2.0,EDUCATION,B,20400,10.25,0,0.25,N,3,False
747,123,78000,RENT,7.0,VENTURE,B,20000,NaN,0,0.26,N,4,True
32297,144,6000000,MORTGAGE,12.0,PERSONAL,C,5000,12.73,0,0.00,N,25,False

In [29]:
df["person_age"].describe()

count    32416.000000
mean        27.747008
std          6.354100
min         20.000000
25%         23.000000
50%         26.000000
75%         30.000000
max        144.000000
Name: person_age, dtype: float64

In [30]:
df["person_age"].value_counts().sort_index().tail(20)

person_age
58     19
59      5
60     15
61      9
62      7
63      3
64      7
65      9
66      9
67      1
69      5
70      7
73      3
76      1
78      1
80      1
84      1
94      1
123     2
144     3
Name: count, dtype: int64

In [31]:
df["person_income"].describe()

count    3.241600e+04
mean     6.609164e+04
std      6.201558e+04
min      4.000000e+03
25%      3.854200e+04
50%      5.500000e+04
75%      7.921800e+04
max      6.000000e+06
Name: person_income, dtype: float64

In [32]:
df["person_income"].sort_values(ascending=False).head(10)

32297    6000000
30049    2039784
32546    1900000
32497    1782000
31924    1440000
31922    1362000
17833    1200000
29120    1200000
29119    1200000
17834     948000
Name: person_income, dtype: int64

In [33]:
df.loc[
    df["person_income"].nlargest(10).index
]

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,interest_rate_missing
32297,144,6000000,MORTGAGE,12.0,PERSONAL,C,5000,12.73,0,0.00,N,25,False
30049,42,2039784,RENT,0.0,VENTURE,C,8450,12.29,0,0.00,Y,15,False
32546,60,1900000,MORTGAGE,5.0,PERSONAL,A,1500,NaN,0,0.00,N,21,True
32497,63,1782000,RENT,13.0,EDUCATION,C,12025,14.27,0,0.01,N,30,False
31924,44,1440000,MORTGAGE,7.0,DEBTCONSOLIDATION,A,6400,7.40,0,0.00,N,15,False
31922,47,1362000,MORTGAGE,9.0,VENTURE,A,6600,7.74,0,0.00,N,17,False
17833,32,1200000,MORTGAGE,1.0,VENTURE,A,12000,7.51,0,0.01,N,8,False
29119,36,1200000,OWN,16.0,MEDICAL,A,10000,6.54,0,0.01,N,11,False
29120,40,1200000,MORTGAGE,1.0,MEDICAL,A,10000,NaN,0,0.01,N,16,True
17834,34,948000,MORTGAGE,18.0,PERSONAL,B,2000,9.99,0,0.00,N,7,False

In [35]:
df["person_age"].isin([123, 144]).sum()

np.int64(5)

In [36]:
df = df[~df["person_age"].isin([123, 144])].copy()

In [37]:
df["person_age"].max()

94

In [38]:
df.shape

(32411, 13)

In [39]:
df["person_emp_length"].describe()

count    31524.000000
mean         4.790350
std          4.145566
min          0.000000
25%          2.000000
50%          4.000000
75%          7.000000
max        123.000000
Name: person_emp_length, dtype: float64

In [40]:
df["person_emp_length"].sort_values().head(10)

11257    0.0
11240    0.0
11211    0.0
11219    0.0
32502    0.0
49       0.0
19392    0.0
32532    0.0
45       0.0
32514    0.0
Name: person_emp_length, dtype: float64

In [41]:
df["loan_amnt"].describe()

count    32411.000000
mean      9593.591682
std       6322.529723
min        500.000000
25%       5000.000000
50%       8000.000000
75%      12250.000000
max      35000.000000
Name: loan_amnt, dtype: float64

In [42]:
df["loan_amnt"].sort_values().head(10)

871      500
18502    500
8607     500
15951    500
1355     500
873      700
18503    725
875      750
3051     800
8346     900
Name: loan_amnt, dtype: int64

In [43]:
df["loan_int_rate"].describe()

count    29317.000000
mean        11.017117
std          3.241845
min          5.420000
25%          7.900000
50%         10.990000
75%         13.470000
max         23.220000
Name: loan_int_rate, dtype: float64

In [44]:
df["person_emp_length"].describe()

count    31524.000000
mean         4.790350
std          4.145566
min          0.000000
25%          2.000000
50%          4.000000
75%          7.000000
max        123.000000
Name: person_emp_length, dtype: float64

In [45]:
df["person_emp_length"].sort_values().head(10)

11257    0.0
11240    0.0
11211    0.0
11219    0.0
32502    0.0
49       0.0
19392    0.0
32532    0.0
45       0.0
32514    0.0
Name: person_emp_length, dtype: float64

In [46]:
(df["person_emp_length"] < 0).sum()

np.int64(0)

In [47]:
df["person_emp_length"].min()

0.0

In [48]:
df["loan_int_rate"].sort_values(ascending=False).head(10)

29277    23.22
27851    22.48
27425    22.11
6449     22.11
13499    22.11
18829    22.06
27633    21.74
2436     21.74
17103    21.74
7470     21.74
Name: loan_int_rate, dtype: float64

In [49]:
(df["loan_int_rate"] <= 0).sum()

np.int64(0)

In [50]:
df["loan_int_rate"].min()

5.42

In [51]:
df["loan_amnt"].describe()

count    32411.000000
mean      9593.591682
std       6322.529723
min        500.000000
25%       5000.000000
50%       8000.000000
75%      12250.000000
max      35000.000000
Name: loan_amnt, dtype: float64

In [52]:
(df["loan_amnt"] <= 0).sum()

np.int64(0)

In [53]:
df["loan_percent_income"].describe()

count    32411.000000
mean         0.170259
std          0.106808
min          0.000000
25%          0.090000
50%          0.150000
75%          0.230000
max          0.830000
Name: loan_percent_income, dtype: float64

In [54]:
(df["loan_percent_income"] <= 0).sum()

np.int64(8)

In [55]:
df.loc[
    df["loan_percent_income"] <= 0,
    ["person_income", "loan_amnt", "loan_percent_income", "loan_status"]
]

       person_income  loan_amnt  loan_percent_income  loan_status
17834         948000       2000                  0.0            0
18917         510000       1800                  0.0            0
27877         522000       2500                  0.0            0
30049        2039784       8450                  0.0            0
31916         780000       1000                  0.0            0
31922        1362000       6600                  0.0            0
31924        1440000       6400                  0.0            0
32546        1900000       1500                  0.0            0

In [56]:
df.loc[
    df["loan_percent_income"] <= 0,
    "calculated_loan_percent_income"
] = (
    df["loan_amnt"] / df["person_income"]
)

df.loc[
    df["loan_percent_income"] <= 0,
    ["loan_amnt", "person_income",
     "loan_percent_income", "calculated_loan_percent_income"]
]

,loan_amnt,person_income,loan_percent_income,calculated_loan_percent_income
17834,2000,948000,0.0,0.002110
18917,1800,510000,0.0,0.003529
27877,2500,522000,0.0,0.004789
30049,8450,2039784,0.0,0.004143
31916,1000,780000,0.0,0.001282
31922,6600,1362000,0.0,0.004846
31924,6400,1440000,0.0,0.004444
32546,1500,1900000,0.0,0.000789

In [57]:
(df["loan_percent_income"] <= 0).sum()

np.int64(8)

In [58]:
mask = df["loan_percent_income"] == 0

df.loc[mask, "loan_percent_income"] = (
    df.loc[mask, "loan_amnt"] /
    df.loc[mask, "person_income"]
)

In [59]:
(df["loan_percent_income"] <= 0).sum()

np.int64(0)

In [60]:
df.loc[
    df.index.isin([17834, 18917, 27877, 30049,
                   31916, 31922, 31924, 32546]),
    ["loan_amnt", "person_income", "loan_percent_income"]
]

       loan_amnt  person_income  loan_percent_income
17834       2000         948000             0.002110
18917       1800         510000             0.003529
27877       2500         522000             0.004789
30049       8450        2039784             0.004143
31916       1000         780000             0.001282
31922       6600        1362000             0.004846
31924       6400        1440000             0.004444
32546       1500        1900000             0.000789

In [61]:
(df["person_emp_length"] < 0).sum()

np.int64(0)

In [62]:
df["person_emp_length"].describe()

count    31524.000000
mean         4.790350
std          4.145566
min          0.000000
25%          2.000000
50%          4.000000
75%          7.000000
max        123.000000
Name: person_emp_length, dtype: float64

In [63]:
df.loc[
    df["person_emp_length"] > 50,
    ["person_age", "person_emp_length", "person_income",
     "loan_status"]
].sort_values("person_emp_length", ascending=False)

     person_age  person_emp_length  person_income  loan_status
0            22              123.0          59000            1
210          21              123.0         192000            0

In [64]:
df = df[df["person_emp_length"] <= df["person_age"]].copy()

In [65]:
df.shape

(31522, 14)

In [66]:
(df["person_emp_length"] > df["person_age"]).sum()

np.int64(0)

In [67]:
df.shape

(31522, 14)

In [68]:
(df["person_emp_length"] > df["person_age"]).sum()

np.int64(0)

In [69]:
df.isnull().sum()

person_age                            0
person_income                         0
person_home_ownership                 0
person_emp_length                     0
loan_intent                           0
loan_grade                            0
loan_amnt                             0
loan_int_rate                      3027
loan_status                           0
loan_percent_income                   0
cb_person_default_on_file             0
cb_person_cred_hist_length            0
interest_rate_missing                 0
calculated_loan_percent_income    31514
dtype: int64

In [70]:
df.duplicated().sum()

np.int64(0)

In [71]:
df.shape

(31522, 14)

In [72]:
df.drop(
    columns=["interest_rate_missing",
             "calculated_loan_percent_income"],
    inplace=True,
    errors="ignore"
)

In [73]:
df.duplicated().sum()

np.int64(0)

In [74]:
df.shape

(31522, 12)

In [75]:
df.duplicated().sum()

np.int64(0)

In [76]:
df.to_csv("creditlens_cleaned.csv", index=False)